<a href="https://colab.research.google.com/github/lyntos/Python_MS_Wilmu_02/blob/main/Week_3_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSC 7002 - Python Programming
## Week 3 Exercises -

> Complete exercises 7.1 - 7.23


In [ ]:
# import NumPy for all exercises
import numpy as np

##**7.1** - (Filling arrays)
Fill a 2-by-3  with ones, a 3-by-3  with zeros and a 2-by-5 array with 7s.

In [ ]:
# create a 2x3 array with ones
ones = np.ones([2,3])

# create a 3x3 array zeroes
zeros = np.zeros([3,3])

# create a 2x5 array with sevens
sevens = np.full([2,5], 7)

# prove desired output
print(ones)
print(zeros)
print(sevens)


[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


##**7.2**(Broadcasting)
Use arrange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array:

>a. Cube every element of the array

>b. Add 7 to every element of the array

>c. Multiply every element of the array by 2


In [ ]:
# create 2x2 array using arange
array = np.arange(4).reshape(2,2)
print(array)

# exercise 7.2.a - cube array elements
cube = array ** 3
print(cube)

# exercise 7.2.b - add 7 to array elements
add_seven = array + 7
print(add_seven)

# exercise 7.2.c - multiply array elements by 2
muliply_two = array * 2
print(muliply_two)

[[0 1]
 [2 3]]
[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


##**7.3** (Element-Wise  Multiplication)
Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array by the second.

In [ ]:
# create first array, print
even_array = np.arange(2,19,2).reshape(3,3)
print(even_array)

# create second array, print
descending_array = np.arange(9,0,-1).reshape(3,3)
print(descending_array)

# print the product of the arrays
print(even_array * descending_array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[18 32 42]
 [48 50 48]
 [42 32 18]]


##**7.4** (array from List of Lists)
Create a 2-by-5 array from an argument which is a list of the two five-element lists [2,3,5,7,11] and [13,17,19,23,29].


In [ ]:
# create a 2x5 array from given lists
list1 = [2,3,5,7,11]
list2 = [13,17,19,23,29]

array = np.array([list1, list2]).reshape(2,5) # reshape is redundant, but proves fit
print(array)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


##7.5 (Flattening arrays with flatten vs. ravel)
Create a 2-by-3 array containing the first six powers of 2 beginning with 2^0. Flatten the array first with method flatten, then with ravel. In each case, display the result then display the original array to show that it was unmodified.

In [ ]:
# create an array of twos
array = np.full([2,3],2)
print(array)

# transform array contents with math
for i in range(2):
  for j in range(3):
    array[i][j] = 2**(i*3+j)

# why this works:
# i * 3 + j = [0] * 3 + [0] = 1
# i * 3 + j = [0] * 3 + [1] = 1
# i * 3 + j = [0] * 3 + [2] = 2
# i * 3 + j = [1] * 3 + [0] = 3
# i * 3 + j = [1] * 3 + [1] = 4
# i * 3 + j = [1] * 3 + [2] = 5

print(array)
print(array.flatten())
print(array.ravel())
print(array)

[[2 2 2]
 [2 2 2]]
[[ 1  2  4]
 [ 8 16 32]]
[ 1  2  4  8 16 32]
[ 1  2  4  8 16 32]
[[ 1  2  4]
 [ 8 16 32]]


##7.6 (Research: array Method astype)
Research in the NumPy documentation the array method astype, which converts an array’s elements to another type. Use linspace and reshape to create a 2-by-3  with the values 1.1, 2.2, ..., 6.6. Then use astype to convert the array to an array of integers.

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html

# create an evenly spaced 2x3 array from 1.1 to 6.6
array = np.linspace(1.1,6.6,6).reshape(2,3)
print(array)

# cast as integer
array = array.astype(int)
print(array)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]


##7.7 (Challenge Project: Reimplement NumPy array Output)
You saw that NumPy outputs two-dimensional arrays in a nice column-based format that right-aligns every element in a field width. The field width’s size is determined by the array element value that requires the most character positions to display. To understand how powerful it is to have this formatting simply built-in, write a function that reimplements NumPy’s array formatting for two-dimensional arrays using loops. Assume the array contains only positive integer values.

In [ ]:
new_array = np.arange(0,100000,5000).reshape(4,5)
print(new_array)

# set max parameters
max_val = new_array[-1,-1] # make the width as wide as the last element
max_width = len(str(max_val)) # width of the string, not the int

# loop through array and print each row, column value
for i in range(4):
  for j in range(5):
    print(f"{new_array[i][j]:>{max_width}}", end=" ") # Use max_width for right-alignment
  print()

[[    0  5000 10000 15000 20000]
 [25000 30000 35000 40000 45000]
 [50000 55000 60000 65000 70000]
 [75000 80000 85000 90000 95000]]
    0  5000 10000 15000 20000 
25000 30000 35000 40000 45000 
50000 55000 60000 65000 70000 
75000 80000 85000 90000 95000 


##7.8 (Challenge Project: Reimplement DataFrame Output)
You saw that pandas displays arrays in an attractive column-based format with row and column labels. The values within each column are right aligned in the same field width, which is determined by that column’s widest value. To understand how powerful it is to have this formatting built-in, write a function that reimplements DataFrame formatting using loops. Assume the DataFrame contains only positive integer values and that both the row and column labels are each integer values beginning at 0.

In [ ]:
'''implement a for loop to mimic a DataFrame output'''
import numpy as np
import pandas as pd

pd_array = np.arange(5000,105000,5000).reshape(4,5)

df = pd.DataFrame(pd_array)
print(df)


# get the widest element of the array by selecting the last element
max_width = len(str(pd_array[-1,-1])) # it is 6 wide because the last element is 100000
#show the value
print(f"Max width = {max_width}\n")

# create a table header to mimic a dataframe

# create a for loop that loops through our array for row (r) and column (c)
for c in range(pd_array.shape[1]+1):
  if c == 0:
    spaces =  ' ' * max_width # print blank spaces in the width of the widest column
    print(f"{spaces:>{max_width}}")
  else:
    actual = c - 1 # we added one to the loop, so subtract one back for correct index
    print(f"{actual:>{max_width}}", end=' ') # print the value right-aligned, 6-wide with a space
print()

# print with a nested loop for each column in each row
for r in range(pd_array.shape[0]):
  print(f"{r}", end=' ')
  for c in range(pd_array.shape[1]):
    print(f"{pd_array[r][c]:>{max_width}}", end=' ')
  print()

# this solution gets really close! the header format needs some work


       0      1      2      3       4
0   5000  10000  15000  20000   25000
1  30000  35000  40000  45000   50000
2  55000  60000  65000  70000   75000
3  80000  85000  90000  95000  100000
Max width = 6

      
     0      1      2      3      4 
0   5000  10000  15000  20000  25000 
1  30000  35000  40000  45000  50000 
2  55000  60000  65000  70000  75000 
3  80000  85000  90000  95000 100000 


## 7.9 (Indexing and Slicing arrays)
Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:
              
                
> a. Select row 2.

> b. Select column 5.
                
> c. Select rows 0 and 1.
                
> d. Select columns 2–4.
                
> e. Select the element that is in row 1 and column 4.
                
> f. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

In [ ]:
#([R:R],[C:C]) -  :, "ignores" R condition, blank ignores C
array = np.arange(1,16).reshape(3,5)
print(array)

# a - select row 2
print("a - select Row 2")
print(array[1])

# b - select column 5
print("b - select Column 5")
print(array[:,4])

# c - select rows 0 and 1
print("c - select Rows 0 and 1")
print(array[0:2])

# d - select columns 2-4
print("d - select Columns 2-4")
print(array[:,2:5])

# e - select element in row 1 column 4
print("e - select Element in Row 1 Column 4")
print(array[1,4]) # confusing terminoligy - could be [0,4] if we mean first row

# f - select all elements from row 1 and 2 in columns 0,2,4
print("f - select All Elements from Rows 1 and 2 in Columns 0,2,4")
print(array[1:3, [0,2,4]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
a - select Row 2
[ 6  7  8  9 10]
b - select Column 5
[ 5 10 15]
c - select Rows 0 and 1
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
d - select Columns 2-4
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
e - select Element in Row 1 Column 4
10
f - select All Elements from Rows 1 and 2 in Columns 0,2,4
[[ 6  8 10]
 [11 13 15]]


## 7.10 (Project: Two-Player, Two-Dimensional Tic-Tac-Toe)
Write a script to play two-dimensional Tic-Tac-Toe between two human players who alternate entering their moves on the same computer. Use a 3-by-3 two-dimensional array. Each player indicates their moves by entering a pair of numbers representing the row and column indices of the square in which they want to place their mark, either an 'X' or an 'O'. When the first player moves, place an 'X' in the specified square. When the second player moves, place an 'O' in the specified square. Each move must be to an empty square. After each move, determine whether the game has been won and whether it’s a draw.

In [ ]:
# create a 2d tic-tac-toe game using arrays
# get numpy
import numpy as np

# create tic tac toe array - blank game board
tic_tac_toe = np.full([3,3], '[ ]')

# create a array of lists with winning combinations
# three in a row vertically, horizontally, or diagonally
winning_combinations = np.array([[0,0],[0,1],[0,2], [1,0],[1,1],[1,2], [2,0],[2,1],[2,2], [0,0],[1,0],[2,0], [0,1],[1,1],[2,1], [0,0], [1,1],[2,2], [0,2],[1,2],[2,2]])

# define a function to check if the played values (i.e. 3 X's or 3 O's) are in the winning_combinations
def check_win(symbol, player):
  '''check for player win conditions'''
  if player == 1:
    symbol = player1
  else:
    symbol = player2
  # check the consecutive array components for win conditions
  if symbol in (winning_combinations):
    return True
  else:
    return False

# initialize players
player1 = 'X'
player2 = 'O'

# playerturn variable to track turns, 1 and 2
# there is probably a more elegant way to accomplish this
playerturn = 1

# gamestatus == 0 if new game, will set to 1 to end game
game_status = 0
number_of_moves = 0 # once at 9 game will end

print('Press enter to play')
input()

# print array with column and row indices
print('Tic Tac Toe')

print(tic_tac_toe)
print('Player 1: X')
print('Player 2: O\n')

# create a while loop to capture player input, continue if the board is not full and
while number_of_moves < 9 and check_win(player1, 1) == False and check_win(player2, 2) == False and game_status == 0:
  # player input
  row = int(input(f'Player {playerturn}, enter row: '))
  col = int(input(f'Player {playerturn}, enter column: '))
  if tic_tac_toe[row][col] == '[ ]':
    # assign symbol based on correct player
    if playerturn == 1:
      tic_tac_toe[row][col] = player1 # assign player 1's move
      number_of_moves += 1 # add number of moves to not go past 9
    else:
      tic_tac_toe[row][col] = player2 # assign player 2's move
      number_of_moves += 1 # add number of moves to not go past 9
    # check win conditions against
    if (check_win(player1, playerturn)): # evaluate if player 1 has a winning combination
      print('Player 1 wins!')
      game_status = 1
    elif (check_win(player2, playerturn)): # evaluate if palyer 2 has a winning combination
      print('Player 2 wins!')
      game_status = 1
    else:
      if playerturn == 1:
        playerturn += 1
      else:
        playerturn -= 1
  else:
    print('Invalid move, try again')

  print(tic_tac_toe, flush = True) # need to update this to write over existing output

  ## TODO - add error handling
  ## TODO - make winning check actually work


Press enter to play

Tic Tac Toe
[['[ ]' '[ ]' '[ ]']
 ['[ ]' '[ ]' '[ ]']
 ['[ ]' '[ ]' '[ ]']]
Player 1: X
Player 2: O

Player 1, enter row: 0
Player 1, enter column: 0
[['X' '[ ]' '[ ]']
 ['[ ]' '[ ]' '[ ]']
 ['[ ]' '[ ]' '[ ]']]
Player 2, enter row: 1
Player 2, enter column: 1
[['X' '[ ]' '[ ]']
 ['[ ]' 'O' '[ ]']
 ['[ ]' '[ ]' '[ ]']]
Player 1, enter row: 2
Player 1, enter column: 2
[['X' '[ ]' '[ ]']
 ['[ ]' 'O' '[ ]']
 ['[ ]' '[ ]' 'X']]
Player 2, enter row: 1
Player 2, enter column: 1
Invalid move, try again
[['X' '[ ]' '[ ]']
 ['[ ]' 'O' '[ ]']
 ['[ ]' '[ ]' 'X']]
Player 2, enter row: 1
Player 2, enter column: 0
[['X' '[ ]' '[ ]']
 ['O' 'O' '[ ]']
 ['[ ]' '[ ]' 'X']]
Player 1, enter row: 2
Player 1, enter column: 0
[['X' '[ ]' '[ ]']
 ['O' 'O' '[ ]']
 ['X' '[ ]' 'X']]
Player 2, enter row: 1
Player 2, enter column: 2
[['X' '[ ]' '[ ]']
 ['O' 'O' 'O']
 ['X' '[ ]' 'X']]
Player 1, enter row: 2
Player 1, enter column: 1
[['X' '[ ]' '[ ]']
 ['O' 'O' 'O']
 ['X' 'X' 'X']]
Player 2, en

KeyboardInterrupt: Interrupted by user

##7.11 (Challenge Project: Tic-Tac-Toe with Player Against the Computer)
Modify your script from the previous exercise so that the computer makes the moves for one of the players. Also, allow the player to specify whether he or she wants to go first or second.

in order to modify the code abocve, we would need to initialize an array of available moves. once that is done, we would need to assign some kind of probability that the program would "select" that, based on win percentage chance if picked.

In [ ]:
'''in order to modify the code above, we would need to initialize an array of available moves. once that is done, we would need to assign some kind of probability that the program would "select" that, based on win percentage chance if picked. '''
# TODO create an array for remaining moves

# generate chance of winning based on remaining moves available



##7.12 (Super Challenge Project: 3D Tic-Tac-Toe with Player Against the Computer)

Develop a script that plays three-dimensional Tic-Tac-Toe on a 4-by-4-by-4 board.
> [Note: This is an extremely challenging project! In the “Deep Learning” chapter, you’ll learn techniques that will help you develop and AI-based approach to solving this problem.]

RA: did not attempt

## 7.13 (Research and Use Other Broadcasting Capabilities)
Research the NumPy broadcasting rules, then create your own arrays to test the rules.

In [ ]:
# numpy broadcasting rules
# https://numpy.org/doc/stable/user/basics.broadcasting.html#broadcasting
import numpy as np

# create arbitrary arrays
array = (0)
array1 = np.array([1,2,3])
array2 = np.array([[1,2],[3,4],[5,6]])
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# broadcast functions
try:
  print(array + array1)
except Exception as e:
  print(e)

try:
  print(array1 + array2)
except Exception as e:
  print(e)

try:
  print(array2 + array3)
except Exception as e:
  print(e)

try:
  print(array2 * array3)
except Exception as e:
  print(e)

try:
  print(array3 + array1)
except Exception as e:
  print(e)

try:
  print(array3 * array) # multiplying by a scalar sets all values to scalar value
except Exception as e:
  print(e)

[1 2 3]
operands could not be broadcast together with shapes (3,) (3,2) 
operands could not be broadcast together with shapes (3,2) (2,2,3) 
operands could not be broadcast together with shapes (3,2) (2,2,3) 
[[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


## 7.14 (Horizontal and Vertical Stacking)
Create the two-dimensional arrays

```python
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])

```

> a. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
                
> b. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
                
> c. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
                
> d. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.

In [ ]:
# create 2d arrays
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])

# a. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.vstack((array1, array2))
print("Array 3: \n",array3)
print(np.shape(array3))
# b. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
array4 = np.hstack((array1,array2))
print("Array 4: \n",array4)
print(np.shape(array4))
# c. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
array5 = np.vstack((array4,array4)).reshape(4,4)
print("Array 5: \n",array5)
print(np.shape(array5))
# d. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
array6 = np.hstack((array3,array3)).reshape(4,4)
print("Array 6: \n",array6)
print(np.shape(array6))

Array 3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
Array 4: 
 [[0 1 4 5]
 [2 3 6 7]]
(2, 4)
Array 5: 
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
(4, 4)
Array 6: 
 [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]
(4, 4)


## 7.15 (Research and Use NumPy’s concatenate Function)
Research NumPy function concatenate, then use it to reimplement the previous exercise.

In [ ]:
# https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy-concatenate
# np.concatenate((a, b), axis=0) - axis = 0 is vertical stack, axis = 1 is horizontal stack

# create 2d arrays
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])

testoutput = np.ndarray((4,4))

# a. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.concatenate((array1, array2), axis = 0)
print("Array 3: \n",array3)
print(np.shape(array3))
# b. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
array4 = np.concatenate((array1,array2), axis = 1)
print("Array 4: \n",array4)
print(np.shape(array4))
# c. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
array5 = np.concatenate((array4,array4), axis = 0).reshape(4,4)
print("Array 5: \n",array5)
print(np.shape(array5))
# d. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
array6 = np.concatenate((array3,array3), axis = 1, out = testoutput).reshape(4,4) # testing the out= argument
print("Array 6: \n",array6)
print(np.shape(array6))

Array 3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)
Array 4: 
 [[0 1 4 5]
 [2 3 6 7]]
(2, 4)
Array 5: 
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
(4, 4)
Array 6: 
 [[0. 1. 0. 1.]
 [2. 3. 2. 3.]
 [4. 5. 4. 5.]
 [6. 7. 6. 7.]]
(4, 4)


##7.16 (Research: NumPy tile Function)
Research and use NumPy’s tile function to create a checkerboard pattern of dashes and asterisks.

In [ ]:
# numpy tile function
# https://numpy.org/doc/stable/reference/generated/numpy.tile.html#numpy.tile

array = np.array([['-','*'], ['*', '-']])
print(np.tile(array, (4,4)))


[['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']]


## 7.17 (Research: NumPy bincount Functions)
Research and use the NumPy bincount function to count the number of occurrences of each non-negative integer in a 5-by-5 array of random integers in the range 0–99.

In [ ]:
# intialize 5-by-5 array of random integers in the range 0–99
array = np.random.randint(0,100,25).reshape(5,5)
print(array)

# flatten the array (count of occurences show up in order 0-99
print(np.bincount(array.flatten()))

# cleanup the output to existing numbers
x = np.where(np.bincount(array.flatten()) > 0)
# print neat output
for x in x[0]:
  print(f'{x}: {np.bincount(array.flatten())[x]}')


[[91 78 13 47 65]
 [11 86 92 14 69]
 [88 19 78  5 80]
 [63 69 41 92 26]
 [73 69 21 64 98]]
[0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 3 0 0 0 1
 0 0 0 0 2 0 1 0 0 0 0 0 1 0 1 0 0 1 2 0 0 0 0 0 1]
5: 1
11: 1
13: 1
14: 1
19: 1
21: 1
26: 1
41: 1
47: 1
63: 1
64: 1
65: 1
69: 3
73: 1
78: 2
80: 1
86: 1
88: 1
91: 1
92: 2
98: 1


## 7.18 (Median and Mode of an array)
NumPy arrays offer a mean method, but not median or mode. Write functions median and mode that use existing NumPy capabilities to determine the median (middle) and mode (most frequent) of the values in an array. Your functions should determine the median and mode regardless of the array’s shape. Test your function on three arrays of different shapes.

###this is outdated - median function exists here: https://numpy.org/doc/stable/reference/generated/numpy.median.html

In [ ]:
# create three differently shaped arrays
array1 = np.random.randint(0,100,6).reshape(1,6)
array2 = np.random.randint(0,100,12).reshape(2,6)
array3 = np.random.randint(0,100,24).reshape(3,8)

# creating median even though it already exists in numpy
def median(array):
  '''find the median of an array - calculated differently for odd (middle) and even (middle two divided by 2)'''
  array.flatten().sort()
  if len(array.flatten()) % 2 == 0:
    return (array.flatten()[int(len(array.flatten())/2)]+array.flatten()[int(len(array.flatten())/2)-1])/2
  else:
    return array.flatten()[int(len(array.flatten())/2)]

# creating mode function becuase it does not exist in numpy
def mode(array):
  '''get the most frequently occuring value'''
  return np.bincount(array.flatten()).argmax()

def display_array(array):
  return array.ravel(array).sort(array)

# display values for validation
display(array1)
# print calculated values
print(f'Median: {median(array1):.2f}\t Mode: {mode(array1):.2f}\n')

# display values for validation
display(array2)
# print calculated values
print(f'Median: {median(array2):.2f}\t Mode: {mode(array2):.2f}\n')

#print values in order for validation
display(array3)
# print calculated values
print(f'Median: {median(array3):.2f}\t Mode: {mode(array3):.2f}\n')


array([[ 4, 39, 62, 90, 22, 42]])

Median: 76.00	 Mode: 4.00



array([[29, 81, 12, 87, 54, 28],
       [61, 65, 77, 48, 77, 92]])

Median: 44.50	 Mode: 77.00



array([[87, 46, 37, 42, 28, 10, 87, 92],
       [20, 80, 11, 34,  7,  9, 84, 52],
       [ 3, 32, 60, 60, 33, 33, 14, 21]])

Median: 20.50	 Mode: 33.00



##7.19 (Enhanced Median and Mode of an array)
Modify your functions from the previous exercise to allow the user to provide an axis keyword argument so the calculations can be performed row-by-row or column-by-column on a two-dimensional array.

In [ ]:
# create functions for row-wise and column-wise median and mean of an array
def row_median(array, x):
  '''calculate the median of each row'''
  if x in (0,1):
  # x is row or column
    return np.median(array, axis = x)
  else:
    return False

def row_mode(array, x):
  '''calculate the mode of each row/column based on axis'''
  if x in (0,1):
  # x is row or column
    if x == 1:
      # row wise mode
      return np.apply_along_axis(lambda x: np.bincount(x).argmax(), 1, array)
    if x == 0:
      # column wise mode
      return np.apply_along_axis(lambda x: np.bincount(x).argmax(), 0, array)
  else:
    return False

# print outputs using all three arrays and 0,1,2 as args
print("Axis: Column")
print(f"Median: {row_median(array1, 1)}")
print(f"Mode: {row_mode(array1, 1)}")
print(f"Median: {row_median(array2, 1)}")
print(f"Mode: {row_mode(array2, 1)}")
print(f"Median: {row_median(array3, 1)}")
print(f"Mode: {row_mode(array3, 1)}")

print("Axis: Row")
print(f"Median: {row_median(array1, 0)}")
print(f"Mode: {row_mode(array1, 0)}")
print(f"Median: {row_median(array2, 0)}")
print(f"Mode: {row_mode(array2, 0)}")
print(f"Median: {row_median(array3, 0)}")
print(f"Mode: {row_mode(array3, 0)}")

print("Axis: Invalid")
print(f"Median: {row_median(array1, 2)}")
print(f"Mode: {row_mode(array1, 2)}")
print(f"Median: {row_median(array2, 2)}")
print(f"Mode: {row_mode(array2, 2)}")
print(f"Median: {row_median(array3, 2)}")
print(f"Mode: {row_mode(array3, 2)}")

# to make this more robust, we should go back and add *args
# this way, if the user does not pass an axis, it will return median and mode
# for the entire array

Median: [40.5]
Mode: [4]
Median: [41.5 71. ]
Mode: [12 77]
Median: [44.  27.  32.5]
Mode: [87  7 33]
Median: [ 4. 39. 62. 90. 22. 42.]
Mode: [ 4 39 62 90 22 42]
Median: [45.  73.  44.5 67.5 65.5 60. ]
Mode: [29 65 12 48 54 28]
Median: [20. 46. 37. 42. 28. 10. 84. 52.]
Mode: [ 3 32 11 34  7  9 14 21]
Median: False
Mode: False
Median: False
Mode: False
Median: False
Mode: False


##7.20 (Performance Analysis)

In this chapter, we used %timeit to compare the average execution times of generating a list of 6,000,000 random die rolls vs. generating an array of 6,000,000 random die rolls.
Though we saw approximately two orders of magnitude performance improvement with , we generated the list and the array using two different random-number generators and different techniques for building each collection. If you use the same techniques we showed to generate a one-element list and a one-element array, creating the list is slightly faster. Repeat the %timeit operations for one-element collections. Then do it again for 10, 100, 1000, 10,000, 100,000 and 1,000,000 elements and compare the results on your system. The table below shows the results on our system, with measurements in nanoseconds (ns), microseconds (us), milliseconds (ms) and seconds (s).

> Textbook table (variance omitted in most columns)
Number of values|List average exection time|array average execution time
--|--|--
1|1.56us +- 25.2ns|1.89us +- 24.4ns
10|11.6us|1.96us
100|109us|3us
1000|1.09ms|12.3us
10000|11.1ms|102us
100000|111ms|1.2ms
1000000|1.1s|10.1ms

This analysis shows why %timeit is convenient for quick performance studies. However, you also need to develop performance-analysis wisdom. Many factors can affect performance—the underlying hardware, the operating system, the interpreter or compiler you’re using, the other applications running on your computer at the same time, and many more. The way we thought about performance over the years is changing rapidly now with big data, data analytics and artificial intelligence. As we head into the AI portion of the book, you’ll place enormous performance demands on your system, so it’s always good to be thinking about performance issues.

In [ ]:
'''using %timeit to count 10, 100, 1000, 10000, 100000, and 1000000 random die rolls
and compare the performance of arrays and lists'''
# import libraries
import numpy as np
import pandas as pd
import random
import timeit

test_array = np.array([10,100,1000,10000,100000,1000000])

# timeit.timeit to create arrays of die rolls from test_array
for i in test_array:
  print(f"{i} elements\narray:")
  print(timeit.timeit(stmt = f'np.random.randint(1,7, {i})', number = 100, globals = globals()))
  print(f"list:")
  #use timeit.timeit and create a list of die rolls frim i
  print(timeit.timeit(stmt = f'random.choices(range(1,7), k = {i})', number = 100, globals=globals()))
  print()


# repeat using %timeit
for i in test_array:
  print(f"{i} elements\narray:")
  %timeit np.random.randint(1,7, i)
  print(f"list:")
  %timeit random.choices(range(1,7), k = i)
  print()



10 elements
array:
0.002097195999795076
list:
0.00026478800009499537

100 elements
array:
0.0010537279999880411
list:
0.0013877480000701325

1000 elements
array:
0.002907569999933912
list:
0.023538250000001426

10000 elements
array:
0.017610746000173094
list:
0.12370591400031117

100000 elements
array:
0.1362849910001387
list:
1.2038651879997815

1000000 elements
array:
1.3339508579997528
list:
13.541757619000236

10 elements
array:
11.6 µs ± 2.5 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
list:
2.04 µs ± 70 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

100 elements
array:
12.6 µs ± 2.85 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
list:
16.2 µs ± 4.37 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)

1000 elements
array:
23.5 µs ± 710 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
list:
148 µs ± 41.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

10000 elements
array:
157 µs ± 21.9 µs per loop (mean ± st

##7.21 (Shallow vs. Deep Copy)
In this chapter, we discussed shallow vs. deep copies of arrays. Python’s built-in list and dictionary types have  methods that perform shallow copies. Using the following dictionary
              
```python
  dictionary = {'Sophia': [97,88]}
```           
                
demonstrate that a dictionary’s  method indeed performs a shallow copy. To do so, call copy to make the shallow copy, modify the list stored in the original dictionary, then display both dictionaries to see that they have the same contents.
                          
 Next, use the  module’s deepcopy function to create a deep copy of the dictionary. Modify the list stored in the original dictionary, then display both dictionaries to prove that each has its own data.

In [ ]:
import numpy as np

dictionary = {'Sophia': [97,88]}

# create an array from dictionary
array = np.array(dictionary['Sophia'])
print(array)

# create a view
array_view = array.view()

# alter the view, print view and original - show that original is CHANGED
array_view[0] = 100
print(array)
print(array_view)


# create a copy, print copy and original - show that original is NOT CHANGED

array_copy = array.copy()
array_copy[0] = 200
print(array)
print(array_copy)



[97 88]
[100  88]
[100  88]
[100  88]
[100  88]
[200  88]


##7.22(Pandas: **Series**) Perform the following tasks with pandas Series:
              
                
>   a. Create a **Series** from the list [7,11,13,17].           
                
>   b. Create a **Series** with five elements that are all 100.0.
                
>   c. Create a **Series** with 20 elements that are all random numbers in the range 0 to 100. Use method **describe** to produce the **Series’** basic descriptive statistics.
                
>   d. Create a **Series** called temperatures of the floating-point values 98.6, 98.9, 100.2 and 97.9. Using the index keyword argument, specify the custom indices 'Julie', 'Charlie', 'Sam' and 'Andrea'.
                
>   e. Form a dictionary from the names and values in Part (d), then use it to initialize a **Series**.

In [ ]:
# refer to section 7.14 of the textbook
import pandas as pd
import numpy as np
# a - create a Series of [7,11,13,17]
series_a = pd.Series([7,11,13,17])
print(series_a)

# b - create a 5-element series of all 100.0
series_b = pd.Series(100.0, index = range(5))
print(series_b)

# c - create a 20 element series of random numbers between 0-100
randoms = np.random.randint(0, 101, 20)
series_c = pd.Series(randoms)

series_c.describe()

# d - create a Series 'temperatures' with 98.6, 98.9, 100.2, 97.9
temperatures = pd.Series([98.6, 98.9, 100.2, 97.9], index = ['Julie', 'Charlie', 'Sam','Andrea'])

# e - create a dictionary using values above, then use it to initialize a series
dictionary = {'Julie': [98.6], 'Charlie':[98.9], 'Sam':[100.2],'Andrea':[97.9]}
# create Series from dictionary
series_e = pd.DataFrame(dictionary)
print(series_e)

0     7
1    11
2    13
3    17
dtype: int64
0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64
   Julie  Charlie    Sam  Andrea
0   98.6     98.9  100.2    97.9


##7.23 (Pandas: DataFrames) Perform the following tasks with pandas DataFrames:
              
> a. Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'.
              
> b. Recreate the DataFrame temperatures in Part (a) with custom indices using the  keyword argument and a list containing 'Morning', 'Afternoon' and 'Evening'.
              
> c. Select from temperatures the column of temperature readings for 'Maxine'.
              
> d. Select from temperatures the row of 'Morning' temperature readings.
              
> e. Select from temperatures the rows for 'Morning' and 'Evening' temperature readings.
              
> f. Select from temperatures the columns of temperature readings for 'Amanda' and 'Maxine'.
              
> g. Select from temperatures the elements for 'Amanda' and 'Maxine' in the 'Morning' and 'Evening'.
              
> h. Use the describe method to produce temperatures’ descriptive statistics.
              
> i. Transpose temperatures.
              
> j. Sort temperatures so that its column names are in alphabetical order.

In [ ]:
import pandas as pd
import numpy as np

# a. Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'.
# values are random 0.1f between 97.0 and 104.0
dictionary_temps = {'Maxine': np.random.uniform(97.0, 104.0,3), 'James': np.random.uniform(97.0, 104.0,3), 'Amanda': np.random.uniform(97.0, 104.0,3)}
temperatures = pd.DataFrame(dictionary_temps)
print(temperatures)
# b. Recreate the DataFrame temperatures in Part (a) with custom indices using the  keyword
# argument and a list containing 'Morning', 'Afternoon' and 'Evening'.

dictionary_temps_time = {'Maxine': np.random.uniform(97.0, 104.0,3), 'James': np.random.uniform(97.0, 104.0,3), 'Amanda': np.random.uniform(97.0, 104.0,3)}
temperatures = pd.DataFrame((dictionary_temps_time), index = ['Morning', 'Afternoon', 'Evening'])
print(temperatures)

# c. Select from temperatures the column of temperature readings for 'Maxine'.
# print column for maxine
print(temperatures[['Maxine']])

# d. Select from temperatures the row of 'Morning' temperature readings.
# print row 'Morning'
print(temperatures.loc[['Morning']])

# e. Select from temperatures the rows for 'Morning' and 'Evening' temperature readings.
print(temperatures.loc[['Morning', 'Evening']])

# f. Select from temperatures the columns of temperature readings for 'Amanda' and 'Maxine'.
print(temperatures[['Amanda', 'Maxine']])

# g. Select from temperatures the elements for 'Amanda' and 'Maxine' in the 'Morning' and 'Evening'.
print(temperatures.loc[['Morning','Evening'],['Amanda','Maxine']])
# h. Use the describe method to produce temperatures’ descriptive statistics.

# i. Transpose temperatures.
print(temperatures.transpose())

# j. Sort temperatures so that its column names are in alphabetical order.
print(temperatures.sort_index(axis = 1))


       Maxine       James      Amanda
0   99.647762   97.541955   97.920381
1   97.376318  101.070099  102.568609
2  100.809103   97.871593  103.438277
               Maxine       James      Amanda
Morning    101.102699  103.360926   97.103285
Afternoon   98.331915  100.300082  102.200343
Evening    101.774603   99.526404   99.816925
               Maxine
Morning    101.102699
Afternoon   98.331915
Evening    101.774603
             Maxine       James     Amanda
Morning  101.102699  103.360926  97.103285
             Maxine       James     Amanda
Morning  101.102699  103.360926  97.103285
Evening  101.774603   99.526404  99.816925
               Amanda      Maxine
Morning     97.103285  101.102699
Afternoon  102.200343   98.331915
Evening     99.816925  101.774603
            Amanda      Maxine
Morning  97.103285  101.102699
Evening  99.816925  101.774603
           Morning   Afternoon     Evening
Maxine  101.102699   98.331915  101.774603
James   103.360926  100.300082   99.526404
Ama

In [ ]:
#